### ISSUE TITLE
Volvo OnCall

### ISSUE THREAD

**Issue by DJay-X** [trympet/homebridge-volvo#1]
@trympet Hope you are doing well.
Any plans for this plugin? I assume you had the idea of having Volvo OnCall features showing up in HomeKit? Just wondering, because I would love to see such a great plugin. :) 

Any news or development on this foreseeable? Thanks.

**Comment by trympet** [comment]
Hey. I am stuffed until the end of the month, but will try to get started by the first of June.
Regarding functionality: turning on the cabin heater with Siri is my top priority 😝, but planning on implementing the same functionality as the official VOC app.

**Comment by DJay-X** [comment]
Thanks for your reply. Your plan sound great. Very looking forward and I will have an eye on you. 😅
Thanks for the time you are investing and sharing with the community. 👍
