### ISSUE TITLE
Option to not expose the climate feature

### ISSUE THREAD

**Issue by chernals** [trympet/homebridge-volvo#12]
It appears that either my car (XC40) does not support remote climate or that it just doesn't work. This is not related to the plugin of course.

However, due to that the Home app will always show the car as not responding although the other services work fine.

Would it be possible to add a configuration option to choose not to expose the climate feature?

Thanks in advance.

**Comment by eckline** [comment]
I'm having the same exact issue. I'm hoping to be able to disable the climate feature somehow from appearing in homekit. Have you found a solution?

**Comment by eckline** [comment]
![Screen Shot 2020-11-30 at 5 28 04 PM](https://user-images.githubusercontent.com/18036242/100673652-ccf5b180-3331-11eb-8890-ded7295f5085.png)

**Comment by chernals** [comment]
I don't have a solution yet unfortunately.

@trympet  Are you still actively maintaining the plugin ? Would it be possible to have a look ?

I will try to submit a PR if I can make it work on my side.

**Comment by burtherman** [comment]
Having same issue with my XC60 T5. I do have the option to turn on “parking climate” normally in the app

**Comment by chernals** [comment]
Unfortunately, it seems that the plugin is not actively maintained anymore.

As a temporary fix for this issue:
 - edit the index.ts (or .js) file at the location where it has been installed by npm (/usr/local/lib/node_modules/homebridge-volvo/dist for example)
 - comment out ( // ) lines 131 and 140
 - restart homebridge

The climate features will go away.

**Comment by nedzalife** [comment]
Not sure what @chernals idea does, but it did not work for me. It ended up causing an issue where my entire homebridge service would not boot.

But, I was able to remove the climate features from showing up in HomeKit by going to:

~/node_modules/homebridge-volvo/dist/util
edit the vehicles.js file 
comment out line 35, which is
`// this.features[types_1.VolvoFeatureBindings.PRECLIMATIZATION] = this.attr.preclimatizationSupported;`
save, reboot homebridge

Hope this helps.

**Comment by di11ard** [comment]
+1 to nedzalife's approach. This works, and allows you to turn on/off different features as desired.

**Comment by gaborkis11** [comment]
> Not sure what @chernals idea does, but it did not work for me. It ended up causing an issue where my entire homebridge service would not boot.
> 
> But, I was able to remove the climate features from showing up in HomeKit by going to:
> 
> /homebridge/node_modules/homebridge-volvo/dist/util
> edit the vehicles.js file
> comment out line 35, which is
> `// this.features[types_1.VolvoFeatureBindings.PRECLIMATIZATION] = this.attr.preclimatizationSupported;`
> save, reboot homebridge
> 
> Hope this helps.

Thanks Your help! It's working for me!
