### ISSUE TITLE
Reduce count of devices in Alexa?

### ISSUE THREAD

**Issue by mschindl** [trympet/homebridge-volvo#13]
Hi,
at first, great plugin! Thank you.

Is it possible to reduce the device count in Alexa?
Feature deactivation didn't help there.

I want to use only the heater/climate feature.

<img width="414" alt="image" src="https://user-images.githubusercontent.com/26382876/102263736-0115c880-3f15-11eb-8f4b-57d65a95b895.png">

**Comment by mschindl** [comment]
"Hide Device" in **<FGDN:port>/accessories** is the solution.

<img width="801" alt="image" src="https://user-images.githubusercontent.com/26382876/102395398-5a482f80-3fdb-11eb-8f57-99698e87edea.png">

**Comment by mschindl** [comment]
Still not solved :/ Any idea?

**Comment by mschindl** [comment]
Still not solved with this function :/ Any idea?

**Comment by trympet** [comment]
Hi @mschindl, sorry for the slow reply.

I agree; having the option to disable and hide each and every accessory is a good idea.

I will look into why the devices are not being disabled, even though they are disabled in the config file.

I will see if I am able to allocate some time later this week to implement this.

I will also look into extending the device registration. Perhaps performing the registration based on enumeration of a list in the configuration file with a unique identifier for every device.

**Comment by hjuhlin** [comment]
Hallo. One ide to also reduce the amount of items can be to have a option to show all windows as one and all doors as one. 

I really like the idea of be able to get a notification when we have forgoten to close a window, but don't really care what window.

**Comment by mschindl** [comment]
@trympet Did you have the time to check why the feature to disable devices/function don't work?
