### ISSUE TITLE
Temperature

### ISSUE THREAD

**Issue by hjuhlin** [trympet/homebridge-volvo#14]
I do not have the opportunity to see the temperature from the car. We do not yet have a weather station connected to our smart home, and then it would be nice to have access to the outdoor temperature from the car for so long.

is that possible?

**Comment by chernals** [comment]
It doesn't seem to be exposed by Volvo On Call. Do you see that information from the car somewhere else? (in the Volvo app?)

**Comment by hjuhlin** [comment]
I can see it in the app. Maybe the app gets it from some weather service?

This is what I see in the app. 

![71C3D73F-3E6F-4E89-8F3E-8A478AC9F122](https://user-images.githubusercontent.com/6752136/103636683-9cb1bc00-4f4a-11eb-9639-8eff6063e1c1.jpeg)

**Comment by chernals** [comment]
I believe it is from a weather service: my car is inside and I see in the app the outside temperature.

**Comment by hjuhlin** [comment]
Aha, that's to bad. Would have been so cool to use the car as temperature sensor outside. But thanks for a very good plug-in.
